name: "budgie"

services:
  budgie:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    env_file: .env
    ports:
      - 9005:80
    depends_on:
    - postgres

  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    volumes:
      - ./storage/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s
